const fortunes = [
    { type: '조언', content: '가장 큰 위험은 아무 위험도 감수하지 않는 것이다.' },
    { type: '조언', content: '오늘 걷지 않으면 내일은 뛰어야 한다.' },
    { type: '조언', content: '성공의 비결은 시작하는 것이다.' },
    { type: '조언', content: '작은 기회로부터 종종 위대한 업적이 시작된다.' },
    { type: '조언', content: '어제를 후회하기보다는 오늘을 감사히 여겨라.' },
    { type: '조언', content: '변화는 우리 삶의 법칙이다.' },
    { type: '조언', content: '당신이 포기할 때, 다른 누군가는 승리한다.' },
    { type: '조언', content: '스스로를 믿는 순간, 어떻게 살아야 할지 알게 된다.' },
    { type: '조언', content: '문제는 멈추는 것이 아니라, 계속 나아가는 것이다.' },
    { type: '조언', content: '가장 어두운 시간은 해가 뜨기 직전이다.' },
    { type: '아이템', content: '오래된 동전' },
    { type: '아이템', content: '반짝이는 돌' },
    { type: '아이템', content: '작은 메모장' },
    { type: '아이템', content: '따뜻한 차 한잔' },
    { type: '아이템', content: '좋아하는 노래' },
    { type: '아이템', content: '편안한 신발' },
    { type: '아이템', content: '창가의 식물' },
    { type: '아이템', content: '오래된 책' },
    { type: '아이템', content: '빈 유리병' },
    { type: '아이템', content: '부드러운 스카프' }
];

const fortune_colors = [
    { name: '석류색', hex: '#E53935' },
    { name: '감귤색', hex: '#F4511E' },
    { name: '호박색', hex: '#FFB300' },
    { name: '금잔화색', hex: '#FDD835' },
    { name: '라임색', hex: '#CDDC39' },
    { name: '비취색', hex: '#4CAF50' },
    { name: '청록색', hex: '#009688' },
    { name: '하늘색', hex: '#03A9F4' },
    { name: '바다색', hex: '#2196F3' },
    { name: '남색', hex: '#3F51B5' },
    { name: '자수정색', hex: '#673AB7' },
    { name: '자홍색', hex: '#9C27B0' },
    { name: '장미색', hex: '#E91E63' },
    { name: '산호색', hex: '#FF5722' },
    { name: '모래색', hex: '#FFC107' },
    { name: '숲의 녹색', hex: '#2E7D32' },
    { name: '황혼색', hex: '#607D8B' },
    { name: '코코아색', hex: '#795548' },
    { name: '은회색', hex: '#BDBDBD' },
    { name: '상아색', hex: '#FFFDE7' }
];
